- name: Provision AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  roles:
    - security_groups
    - target_group
    - alb
    - ec2
    - target_registration


- name: Configure Nginx Servers In Private EC2
  hosts: web
  become: yes
  gather_facts: true

  roles:
    - nginx
